sudo: required
dist: bionic
language: python
python: '3.6'
install: git clone -b travis-gentoo https://github.com/fepitre/qubes-builder ~/qubes-builder
script: ~/qubes-builder/scripts/travis-build
env:
 - DISTS_VM=gentoo GENTOO_MIRROR=https://mirror.notset.fr/gentoo/qubes/gnome GENTOO_MIRROR_KEY=9FA64B92F95E706BF28E2CA6484010B5CDC576E2
 - DISTS_VM=gentoo+minimal GENTOO_MIRROR=https://mirror.notset.fr/gentoo/qubes/minimal GENTOO_MIRROR_KEY=9FA64B92F95E706BF28E2CA6484010B5CDC576E2
 - DISTS_VM=gentoo+xfce GENTOO_MIRROR=https://mirror.notset.fr/gentoo/qubes/xfce GENTOO_MIRROR_KEY=9FA64B92F95E706BF28E2CA6484010B5CDC576E2